#!/usr/bin/env bash
. "$(dirname $0)/kms_functions"

[ -z "$1" ] && { 
    echo -e "Kill processes softly by name matching pattern."
    echo -e "usage: $(basename "${0}") first_pgrep_pattern [second_pgrep_pattern] <...> \n"
    exit 1
}

while (( "$#" )); do
    PROCESS_PIDS=($(pgrep $1))
    [ "${#PROCESS_PIDS[@]}" -gt 1 ] && { echo "More than one process matches $1, won't kill multiple processes"; shift; continue; }
    [ "${#PROCESS_PIDS[@]}" -eq 0 ] && { echo "No process matches given pattern $1"; shift; continue; }
    PID=${PROCESS_PIDS[0]}
    killmesoftly ${PID}
    shift
done
