#!/usr/bin/env bash

function realpath {
    if [ `uname` == "Darwin" ]; then
        # if symlink, resolve it, otherwise just echo back filepath
        realfile=$(readlink "$1")
        if [ $? -eq 0 ]; then echo "$realfile"; else echo "$1"; fi
    else 
        readlink -f "$1"
    fi
}

. "$(dirname "$(realpath "${BASH_SOURCE[0]}")")/kms_functions"

[ -z "$1" ] && { 
    echo -e "Kill processes softly by pid number"
    echo -e "usage: $(basename "${0}") first_pid_to_kill [second_pid_to_kill] <...>\n"
    exit 1
}

while (( "$#" )); do
    [[ ! "$1" =~ ^[0-9]+$ ]] && { echo "Invalid process pid ${1}, skipping"; shift; continue; }
    checkPsExists $1 || { echo "PID ${1} not found among running processes, skipping"; shift; continue; }
    killmesoftly $1
    shift
done
